name: Realase

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Build
        run: |
          bun build
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/*.zip
      - name: Changelog
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
