name: Realase

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Build
        run: |
          bun run build
      - run: bunx changelogithub --assets build/*.zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
